CREATE TABLE USER_INVESTMENTS (
	USR_NM varchar(32) NOT NULL PRIMARY KEY,
	INVSTMNT_NM varchar(64) NOT NULL,
	IS_POSITIVE bit NOT NULL,
	INVSTMNT_AMT float NOT NULL,
	INVSTMNT_NOTES varchar(1024) NOT NULL,
	UPDT_TS datetime2 NOT NULL
);